version: "2.2"

volumes:
  postgres:
  redis:

services:
  api:
    build: ./api
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    ports:
      - 4000:3000
    volumes:
      - ./api:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  web:
    build: ./web
    command: yarn run dev
    ports:
      - 4001:9000
    volumes:
      - ./web:/app
    env_file:
      - .env
    mem_limit: 4g

  postgres:
    image: postgres:9.6.6-alpine
    ports:
      - 5051:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:4.0.2-alpine
    command:
      - redis-server
      - --appendonly
      - "yes"
    volumes:
      - redis:/data
